### PR TITLE
Improve form control

### PR DESCRIPTION
**Pull request by vv181**
I fixed the `public_uri` not passed in case of form error, so I pass the whole context.

Also, I add the proper HTML input type.

### CODE REVIEW

**Review by cnohall — APPROVED** [review]
Looks good, several small but important details are fixed. 

- Better error handling
- Updated HTML Title (Satoshibox -> File Shop)
- Price > 0
- Email form now only accepts strings of the _email_ type.

**Comment by blockonomics** [comment]
@vv181 A total of 20USD has been accumulated for your *3 easy PR* fixes till date. Feel free to state your bitcoin address to withdraw or you can continue progress and withdraw later

**Comment by vv181** [comment]
> @vv181 A total of 20USD has been accumulated for your _3 easy PR_ fixes till date. Feel free to state your bitcoin address to withdraw or you can continue progress and withdraw later

Sure, here is my address: bc1qhnqgfmma6y00ksw9ktpzvvpqut0sa4d8n7y726
Thanks

**Comment by shivaenigma** [comment]
Paid [20 USD](https://www.blockonomics.co/api/tx?txid=1819ca971d992e87df59c237d1916402ce6dbe0d51dd3236c5a6b02164034f70&addr=bc1qhnqgfmma6y00ksw9ktpzvvpqut0sa4d8n7y726)

**Pull request merged**
