### PR TITLE
Added wrapper for configuration variable

### PR DESCRIPTION
**Pull request by nerding-it**
- Added new config module to abstract the configuration
- Updated settings accordingly

### CODE REVIEW

**Comment by blockonomics** [comment]
Can you explain the _motivation/advantage_ of  moving things to config.py and using environment variables.
Few disadvantages:
- Export is a non preferred way to specify settings. Windows users don't use env.  
- This now requires a seperate launching script to set those variables before all django as we want to keep our local configuration saved in a file. Something like [config/ini file](https://stackoverflow.com/questions/5055042/whats-the-best-practice-using-a-settings-file-in-python) is more standard. The config file should of course not be added to the git repo

**Comment by nerding-it** [comment]
Main motivation/advantages are below

1. It's not config file, It's a wrapper to load configuration into python
dictionary.
2. Any other configurations like ini or .env is just for development, When
it moved to some cloud instances obviously it will use some config service
like hashicorp vault
3. Since all configuration are loaded at one place it's easy to validate
and throw an error before application launch
4. Basic idea is to abstract app configuration from application code, So
application is completely don't aware where configurations are coming from
may be local ini or from third party services.
5. Configuration can be added to git repo but one should not commit secret
information like api keys

Thanks
Sriharsha

**Comment by nerding-it** [comment]
Just missed one explanation, 

- Technically environment variables are part of the OS or shell instance
- That means outside of the application these are accessible
- If you look for some service like https://www.vaultproject.io/ it solves such a problem, So that secret information is not accessible outside of the application
I hope this helps

**Comment by blockonomics** [comment]
Appreciate your thoughts. Such complexity is not required. 
We prefer [local setttings approach](https://stackoverflow.com/a/1629770/5043010). It is not tracked in git and values can easily be set in local/production. If abstraction is required, local_settings can also load config from other server/file as required.

**Pull request closed without merging**
